### ISSUE TITLE
Licitações de Empresas que forneceram tornozeleiras

### ISSUE THREAD

**Issue by nicholasess** [rafapetter/suspeitando#3]
@rafapetter gostaria de saber onde encontro as licitações de cada estado ou do Brasil inteiro para o nicho de tornozeleiras eletronicas.

Obrigado

**Comment by rafapetter** [comment]
Oi @nicholasess, eu não conheço. Minha sugestão seria dar uma consultada com o pessoal do Observatório Social: http://osbrasil.org.br/

**Comment by nicholasess** [comment]
@rafapetter obrigado

abs
